# Generated by Django 4.2.9 on 2024-02-13 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='email',
            field=models.EmailField(default='abc@gmail.com', max_length=254),
        ),
        migrations.AddField(
            model_name='usermodel',
            name='firstname',
            field=models.CharField(default='firstname', max_length=30),
        ),
        migrations.AddField(
            model_name='usermodel',
            name='lastname',
            field=models.CharField(default='lastname', max_length=30),
        ),
        migrations.AddField(
            model_name='usermodel',
            name='phone',
            field=models.IntegerField(default=1234),
        ),
    ]
