# Generated by Django 4.2.9 on 2024-02-13 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoApp', '0003_alter_usermodel_email_alter_usermodel_firstname_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='slug',
            field=models.SlugField(default=''),
        ),
    ]
